# Generated by Django 2.2 on 2019-04-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
