# Generated by Django 2.2 on 2019-05-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_question_answers_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers_count',
        ),
    ]
